{
        "name" : "Minzoto médical - CRF MOKUWA",
        "version" : "1.0",
        "author" : "MINZOTOTECH Sarl",
        "website" : "http://minzototech.com",
        "category" : "medical",
        "description": """  """,
        "depends" : ['mz_medical','mz_medical_facturation_categorie_patient'],
        "data" : [
                'security/kine_security.xml',
                'views/infirmier_view.xml',
                'views/secretaire_view.xml',
                'views/cabinet_medical_view.xml',
                'views/labo_view.xml',
                'views/facture_view.xml',
                'views/dossier_traitement_view.xml',
                'views/patient_view.xml',
                'views/facture_proforma_view.xml',
                'views/caisse_view.xml',
                'views/dossier_kine_readaptation.xml',
                'views/acte_view.xml',
                'wizard/validation_don.xml',
                'wizard/prescription_actes.xml',
                'views/layouts.xml',
                'data/data_categorie_patient.xml',
                'data/data_stade_mobilite_passive.xml',
                'security/ir.model.access.csv',
                ],
        "qweb": [ ],
        "js": [  ],
        "css": [ ],
        "installable": True,
        "application": True
}
